---
build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bullseye
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PIPER_LIB_VERSION: 0.0.2
  PIPER_RELEASE: v0.0.2
