---
version: 0.1.0
slug: piper
name: Piper
description: Text-to-speech with Piper
url: https://github.com/home-assistant/addons/blob/master/piper
arch:
  - amd64
  - aarch64
init: false
#discovery:
#  - wyoming
options:
  voice: en-us-lessac-low
  speaker: 0
  length_scale: 1.0
  noise_scale: 0.667
  noise_w: 0.333
schema:
  voice: |
    list(ca-upc_ona-x-low|ca-upc_pau-x-low|da-nst_talesyntese-medium|de-eva_k-x-low|de-thorsten-low|en-gb-alan-low|en-gb-southern_english_female-low|en-us-amy-low|en-us-kathleen-low|en-us-lessac-low|en-us-lessac-medium|en-us-libritts-high|en-us-ryan-high|en-us-ryan-low|en-us-ryan-medium|es-carlfm-x-low|fi-harri-low|fr-siwis-low|fr-siwis-medium|it-riccardo_fasol-x-low|kk-iseke-x-low|kk-issai-high|kk-raya-x-low|ne-google-medium|ne-google-x-low|nl-mls_7432-low|nl-nathalie-x-low|nl-rdh-medium|nl-rdh-x-low|no-talesyntese-medium|pl-mls_6892-low|pt-br-edresson-low|uk-lada-x-low|vi-25hours-single-low|vi-vivos-x-low|zh-cn-huayan-x-low)
  speaker: int
  length_scale: float
  noise_scale: float
  noise_w: float
ports:
  "10200/tcp": null
homeassistant: 2023.5.0.dev20230418
image: homeassistant/{arch}-addon-piper
