build_from:
  aarch64: homeassistant/aarch64-base:3.11
  amd64: homeassistant/amd64-base:3.11
  armhf: homeassistant/armhf-base:3.11
  armv7: homeassistant/armv7-base:3.11
  i386: homeassistant/i386-base:3.11
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  NOVNC_VERSION: 1.2.0
  OZW_VERSION: ee90c896c137b3a473232565c45a51d70c41c431
  QTMQTT_VERSION: 5.12.8
  QTOZWADMIN_VERSION: f68b43ec162f6eb59173710e00b1f1aa192ce373
  QTOZW_VERSION: 7ebd43e246e97851ad20f2b1bb9c62bfd6a4a6ef
  QTWEBSOCKETS_VERSION: 5.12.8
  WEBSOCKIFY_VERSION: 0.9.0
