arch:
- amd64
- i386
- armhf
- armv7
- aarch64
description: Control a ZWave network with Home Assistant
discovery:
- ozw
homeassistant: 0.110.0.dev
image: homeassistant/{arch}-addon-zwave
ingress: true
ingress_entry: vnc_lite.html
init: false
name: OpenZWave
options:
  device: null
  network_key: ''
panel_icon: mdi:z-wave
panel_title: OpenZWave
ports:
  1983/tcp: null
  5900/tcp: null
ports_description:
  1983/tcp: ozw-admin port
  5900/tcp: VNC port
schema:
  device: device(subsystem=tty)
  instance: int(1,)?
  network_key: password
services:
- mqtt:want
slug: zwave
stage: experimental
startup: services
url: https://github.com/home-assistant/hassio-addons/tree/master/zwave
version: 0.9.1

