language: bash

sudo: required
service: docker

addons:
  apt:
    packages:
     - docker-ce
     - jq

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/addons koalaman/shellcheck /addons
 - bash -c 'shopt -s globstar ; jq . **/*.json'

matrix:
  fast_finish: true
