language: bash

sudo: required
service: docker

addons:
  apt:
    packages:
     - docker-ce
     - jq

before_install:
  - shopt -s globstar
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/mnt koalaman/shellcheck **/*.sh
 - jq . **/config.json'
 - jq . **/build.json'

matrix:
  fast_finish: true
