language: bash

sudo: required
service: docker

addons:
  apt:
    packages:
     - docker-ce

before_install:
  - shopt -s globstar
  - docker pull koalaman/shellcheck

script:
 - docker run -v $(pwd):/mnt koalaman/shellcheck **/*.sh

matrix:
  fast_finish: true
