---
version: 0.1.0
slug: silabs_flasher
name: Silicon Labs Flasher
description: Silicon Labs firmware flasher add-on
url: >
  https://github.com/home-assistant/addons/tree/master/silabs_flasher
arch:
  - armv7
  - aarch64
  - amd64
gpio: true
hassio_api: true
image: homeassistant/{arch}-addon-silabs-flasher
init: false
options:
  device: null
  bootloader_baudrate: "115200"
  flow_control: true
schema:
  device: device(subsystem=tty)?
  bootloader_baudrate: list(57600|115200|230400|460800|921600)
  flow_control: bool?
  firmware_url: str?
stage: experimental
startup: once
