arch:
- armhf
- armv7
- aarch64
- amd64
- i386
description: Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support
image: homeassistant/{arch}-addon-duckdns
map:
- ssl:rw
name: Duck DNS
options:
  aliases: []
  domains:
  - null
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
  token: null
schema:
  aliases:
  - alias: str
    domain: str
  domains:
  - match(.+\.duckdns\.org)
  ipv4: str?
  ipv6: str?
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  token: str
slug: duckdns
startup: services
url: https://github.com/home-assistant/hassio-addons/tree/master/duckdns
version: 1.14.0

