arch:
- amd64
- i386
- armv7
- aarch64
audio: true
description: Turn your device into a Media Player with VLC
discovery:
- vlc_telnet
homeassistant: 2021.3.0.dev20210216
image: homeassistant/{arch}-addon-vlc
ingress: true
init: false
map:
- share:ro
- media:ro
name: VLC
options: {}
panel_icon: mdi:vlc
schema: false
slug: vlc
stage: experimental
startup: services
url: https://github.com/home-assistant/hassio-addons/tree/master/vlc
version: 0.1.3

