name: "Wyoming Piper"
slug: "wyoming_piper"
description: "Local text to speech with Piper"
version: "0.0.1"
arch:
  - "amd64"
  - "aarch64"
init: false
options:
  voice: "en-us-ryan-low"
  speaker: 0
schema:
  voice: "list(ca-upc_ona-x-low|ca-upc_pau-x-low|da-nst_talesyntese-medium|de-eva_k-x-low|de-thorsten-low|en-gb-alan-low|en-gb-southern_english_female-low|en-us-amy-low|en-us-kathleen-low|en-us-lessac-medium|en-us-libritts-high|en-us-ryan-high|en-us-ryan-low|en-us-ryan-medium|es-carlfm-x-low|fi-harri-low|fr-siwis-low|fr-siwis-medium|it-riccardo_fasol-x-low|kk-iseke-x-low|kk-issai-high|kk-raya-x-low|ne-google-medium|ne-google-x-low|nl-nathalie-x-low|nl-rdh-medium|nl-rdh-x-low|no-talesyntese-medium|pl-mls_6892-low|uk-lada-x-low|vi-25hours-single-low|vi-vivos-x-low|zh-cn-huayan-x-low)"
  speaker: "int"
map:
  - "share:rw"
ports:
  "10200/tcp": 10200
