# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - dhcp_server/*
pr: none

variables:
  - name: versionBuilder
    value: "2.0"
  - group: docker

jobs:
  - template: /.azure/azp-template-addon.yml
    parameters:
      addon: "dhcp_server"
      arch: "--all"
