build_from:
  aarch64: homeassistant/aarch64-base:3.10
  amd64: homeassistant/amd64-base:3.10
  armhf: homeassistant/armhf-base:3.10
  armv7: homeassistant/armv7-base:3.10
  i386: homeassistant/i386-base:3.10
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
