arch:
- armv7
- aarch64
- amd64
audio: true
description: The open-source, privacy-preserving voice assistant
discovery:
- almond
homeassistant: 0.102.0
homeassistant_api: true
image: homeassistant/{arch}-addon-almond
ingress: true
init: false
name: Almond
panel_icon: mdi:comment-eye-outline
slug: almond
url: https://github.com/home-assistant/hassio-addons/blob/master/almond
version: 2.0.1

