# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - google_assistant/*
pr: none

variables:
  - name: versionBuilder
    value: "2.0"
  - group: docker

jobs:
  - template: /.azure/azp-template-addon.yml
    parameters:
      addon: "google_assistant"
      arch: "--armv7 --armhf --amd64"
