build_from:
  armv7: homeassistant/armv7-base-debian:bullseye
  i386: homeassistant/i386-base-debian:bullseye
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  OCCU_VERSION: 3.59.6
