build_from:
  aarch64: homeassistant/aarch64-base-debian:buster
  amd64: homeassistant/amd64-base-debian:buster
  armhf: homeassistant/armhf-base-raspbian:buster
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  DECONZ_VERSION: 2.12.06
