---
build_from:
  aarch64: ghcr.io/hassio-addons/base:12.2.4
  amd64: ghcr.io/hassio-addons/base:12.2.4
  armhf: ghcr.io/hassio-addons/base:12.2.4
  armv7: ghcr.io/hassio-addons/base:12.2.4
  i386: ghcr.io/hassio-addons/base:12.2.4
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  ZWAVEJS_SERVER_VERSION: 1.22.1
  ZWAVEJS_VERSION: 10.1.0
