arch:
- armhf
- armv7
- aarch64
- amd64
- i386
backup_post: /bin/s6-svc -wd -d /run/s6/services/mariadb-lock/
backup_pre: /bin/s6-svc -wU -u /run/s6/services/mariadb-lock/
description: A SQL database server
image: homeassistant/{arch}-addon-mariadb
init: false
name: MariaDB
options:
  databases:
  - homeassistant
  logins:
  - password: null
    username: homeassistant
  rights:
  - database: homeassistant
    username: homeassistant
ports:
  3306/tcp: null
schema:
  databases:
  - str
  logins:
  - password: password
    username: str
  rights:
  - database: str
    privileges:
    - list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|CREATE VIEW|DELETE|DELETE
      HISTORY|DROP|EVENT|GRANT OPTION|INDEX|INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?
    username: str
services:
- mysql:provide
slug: mariadb
startup: system
timeout: 20
url: https://github.com/home-assistant/hassio-addons/tree/master/mariadb
version: 2.4.0

