# https://dev.azure.com/home-assistant

trigger:
  branches:
    include:
    - testing
  paths:
    include:
    - /*
pr: none

variables:
  - name: versionBuilder
    value: '2.0'

jobs:

- job: 'letsencrypt'
  condition: eq(variables['Build.SourceBranchName'], 'testing')
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo docker login -u $(dockerUser) -p $(dockerPassword)
    displayName: 'Docker hub login'
  - script: sudo docker pull homeassistant/amd64-builder:$(versionBuilder)
    displayName: 'Install Builder'
  - script: |
      sudo docker run --rm --privileged \
        -v ~/.docker:/root/.docker \
        -v /run/docker.sock:/run/docker.sock:rw -v $(pwd):/data:ro \
        homeassistant/amd64-builder:$(versionBuilder) \
        --addon --all -t /data/letsencrypt \
        --docker-hub zapfmeister --docker-hub-check
    displayName: 'Build letsencrypt'
