build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.9-alpine3.14
  amd64: ghcr.io/home-assistant/amd64-base-python:3.9-alpine3.14
  armhf: ghcr.io/home-assistant/armhf-base-python:3.9-alpine3.14
  armv7: ghcr.io/home-assistant/armv7-base-python:3.9-alpine3.14
  i386: ghcr.io/home-assistant/i386-base-python:3.9-alpine3.14
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  CERTBOT_DNS_DIRECTADMIN_VERSION: 0.0.13
  CERTBOT_DNS_TRANSIP_VERSION: 0.3.0
  CERTBOT_GANDI_VERSION: 1.2.5
  CERTBOT_NETCUP_VERSION: 0.31.0.1
  CERTBOT_NJALLA_VERSION: 0.0.4
  CERTBOT_VERSION: 1.2.0
